### ISSUE TITLE
Faute d'indexes 

### ISSUE THREAD

**Issue by ArthurZucker** [Bertbk/course-fem-sphinx#1]
Une petite erreur d'écriture il me semble dans la partie : `Mise en oeuvre`, à la section `Calcul des Matrices Élémentaires`, partie `triangle de référence` dans le Lemme : $$ \Meh_{i,j} = \int_{\trih} \mphih_j(\xi)\mphih_j(\eta) \diff(\xi,\eta) $$ devrait être $$ \Meh_{i,j} = \int_{\trih} \mphih_j(\xi,\eta)\mphih_j(\xi,\eta) \diff(\xi,\eta) $$

**Comment by Bertbk** [comment]
C'est corrigé, merci !
