### ISSUE TITLE
Matrice 'K' désormais matrice 'D'

### ISSUE THREAD

**Issue by ArthurZucker** [Bertbk/course-fem-sphinx#2]
L'erreur se trouve ligne `42` du fichier `contributions-elementaires.rst` : 

> Nous nous focalisons sur la matrice de masse, le principe est similaire pour la matrice :math:`K` et est détaillé juste après.

à remplacer par : 

> Nous nous focalisons sur la matrice de masse, le principe est similaire pour la matrice :math:`D` et est détaillé juste après.

**Comment by Bertbk** [comment]
Merci c'est corrigé !
